### ISSUE TITLE
Basic Example Not Working as Expected on Android

### ISSUE THREAD

**Issue by MurtazaEliyas** [LucasMonteiro1/react-native-speedometer-chart#18]
I was looking through speedometer libraries and came across this library. Very simple and clean. How ever when I try to run the basic example in my android application the meter does not fill in correctly. See image
![Screenshot_1569741761](https://user-images.githubusercontent.com/31281210/65828397-d5201000-e29a-11e9-9f83-aac57defa3c9.png)

Note in the image above i have copied the exact example. Code is as follows:
` <Speedometer value={25} totalValue={100}/>`

Just to test further I took a little more complex example from read me having the same issue. See image.
![Screenshot_1569741962](https://user-images.githubusercontent.com/31281210/65828437-3942d400-e29b-11e9-8a6b-2043f97a13e4.png)

Note in the image above i have copied the exact example. Code is as follows:
`  <Speedometer
    value={50}
    totalValue={150}
    size={250}
    outerColor="#d3d3d3"
    internalColor="#ff0000"
    showText
    text="50.00"
    textStyle={{ color: 'green' }}
    showLabels
    labelStyle={{ color: 'blue' }}
    showPercent
    percentStyle={{ color: 'red' }}
  />`

Here is my package.json snippet

`"react": "16.8.6",
 "react-native": "0.60.5",
"react-native-speedometer-chart": "^0.7.3",`

Would appreciate if someone could support on this.

**EDIT**
When total value is set as `totalValue={150}` it renders 1500. Which is weird. Also the base nuber does not render if you notice (the zero).

**Comment by LucasMonteiro1** [comment]
Hi @MurtazaEliyas, I released version v0.7.4 with some fixes and updated the [Expo example](https://expo.io/@lucasmonteiro1/speedometer-chart-example), can try again? 

If error persists, publish repository in GitHub or send me an email with source code with error, please.
