### ISSUE TITLE
Is it possible to set the inner circle to transparent?

### ISSUE THREAD

**Issue by uneeb123** [LucasMonteiro1/react-native-speedometer-chart#2]
Seems like there is no way to adjust the color of the inner circle.

**Comment by LucasMonteiro1** [comment]
You can now change the color of the inner circle. Released on 0.6.2

**Comment by nidhinkumar06** [comment]
@LucasMonteiro1  How to do the same with a needle and different colors in inner circle

**Comment by vishal767** [comment]
I want to match the inner circle to a background of the view...which is a gradient ...how is it possible?
