### ISSUE TITLE
How to reduce the thickness of meter?

### ISSUE THREAD

**Issue by devtechvalens** [LucasMonteiro1/react-native-speedometer-chart#4]
Hey Developer,

You have created awesome library, i am just looking to reduce the thickness of meter.

Please let me know how can i do that.

Looking forward to hear from you!
Thanks

**Comment by LucasMonteiro1** [comment]
Hi, now it's possible with version 0.6.4
```bash
npm install --save react-native-speedometer-chart@0.6.4
```
and passing `percentSize` property (Default is 0.5)
```
<Speedometer value={25} totalValue={100} percentSize={0.8} />
```
Thanks for your contact!
