### ISSUE TITLE
I wanted a needle on this guage chart

### ISSUE THREAD

**Issue by saurabhperiwal** [LucasMonteiro1/react-native-speedometer-chart#6]
I wanted a needle on this Guage chart, something like 
![screenshot 2019-02-06 at 11 34 57 am](https://user-images.githubusercontent.com/8395849/52323507-4442ae80-2a03-11e9-9b1d-76781f4cdf76.png)

**Comment by WesleyFaveri** [comment]
#7

**Comment by WesleyFaveri** [comment]
I sent a pull request #7

**Comment by LucasMonteiro1** [comment]
Merged #7 and published [v0.7.1](https://www.npmjs.com/package/react-native-speedometer-chart/v/0.7.1)
