### ISSUE TITLE
Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `Speedometer`, expected `object`.

### ISSUE THREAD

**Issue by AmirolAhmad** [LucasMonteiro1/react-native-speedometer-chart#8]
because default for style is `{}`

**Comment by LucasMonteiro1** [comment]
Thank you for reporting @AmirolAhmad! I'll be fixing in the next build.

**Comment by LucasMonteiro1** [comment]
Released [v0.7.2](https://github.com/LucasMonteiro1/react-native-speedometer-chart/releases/tag/v0.7.2) for fix.
