### ISSUE TITLE
needle example doesn't work

### ISSUE THREAD

**Issue by PavloPoliakov** [LucasMonteiro1/react-native-speedometer-chart#9]
Hello,

I'm not sure needle works as expected, please check. Here is a demo app:
https://snack.expo.io/ryaSaE4vN

Thanks for the library.

Regards,

**Comment by LucasMonteiro1** [comment]
I published version 0.7.3 to fix this. Try it out [speedometer-chart-example](https://expo.io/@lucasmonteiro1/speedometer-chart-example).
